#!/bin/bash

set -euo pipefail

cd "$(dirname "$0")"

source="$HOME/.gitconfig-shared"
target="$(pwd)/gitconfig"
if (! stat -q "$source" > /dev/null) || [ "$(grealpath "$source")" != "$target" ]; then
  echo "creating symlink at ${source/$HOME/~}..."
  rm -f "$source"
  ln -s "$target" "$source"
else
  echo "${source/$HOME/~} symlink already up-to-date"
fi

if (! stat -q ~/.gitconfig > /dev/null) || (! grep -q -E 'path *= *.gitconfig-shared' ~/.gitconfig); then
  echo "adding include to ~/.gitconfig..."
  echo "
[include]
  path = .gitconfig-shared
" >> ~/.gitconfig
else
  echo "~/.gitconfig already up-to-date"
fi

if ! command -v delta > /dev/null; then
  echo "installing delta..."
  brew install delta
else
  echo "delta already installed"
fi

if ! command -v difft > /dev/null; then
  echo "installing difftastic..."
  brew install difftastic
else
  echo "difftastic already installed"
fi

echo "done!"
