alias t='t_time_tracker'
alias b='afplay /System/Library/Sounds/Glass.aiff -v 2'
alias n='osascript -e "display notification with title \"Task Finished\""'
alias f='find . -iname '
alias jsonpretty='python -m json.tool'
alias gimme-usrlocal='sudo chown -R skelley /usr/local/{lib,bin,share}'
