#!/bin/bash

set -euo pipefail

cd "$(dirname "$0")"

source="$HOME/Library/Application Support/Code/User"
target="$(dirname "$(pwd)")/vscode"
if (! stat -q "$source" > /dev/null) || [ "$(grealpath "$source")" != "$target" ]; then
  echo "creating symlink at ${source/$HOME/~}..."
  rm -r "$source"
  ln -s "$target" "$source"
else
  echo "${source/$HOME/~} symlink already up-to-date"
fi

echo "done!"
