#!/bin/bash

set -euo pipefail

cd "$(dirname "$0")"

source="$HOME/.claude"
target="$(pwd)/claude"
if (! stat -q "$source" > /dev/null) || [ "$(grealpath "$source")" != "$target" ]; then
  echo "creating symlink at ${source/$HOME/~}..."
  rm -f "$source"
  mkdir -p "$(dirname "$source")"
  ln -s "$target" "$source"
else
  echo "${source/$HOME/~} symlink already up-to-date"
fi

source="$HOME/Library/Developer/Xcode/CodingAssistant/ClaudeAgentConfig/skills"
target="$(pwd)/common/skills"
if (! stat -q "$source" > /dev/null) || [ "$(grealpath "$source")" != "$target" ]; then
  echo "creating symlink at ${source/$HOME/~}..."
  rm -f "$source"
  mkdir -p "$(dirname "$source")"
  ln -s "$target" "$source"
else
  echo "${source/$HOME/~} symlink already up-to-date"
fi

source="$HOME/.codex/AGENTS.md"
target="$(pwd)/common/AGENTS.md"
if (! stat -q "$source" > /dev/null) || [ "$(grealpath "$source")" != "$target" ]; then
  echo "creating symlink at ${source/$HOME/~}..."
  rm -f "$source"
  mkdir -p "$(dirname "$source")"
  ln -s "$target" "$source"
else
  echo "${source/$HOME/~} symlink already up-to-date"
fi

source="$HOME/.agents/skills"
target="$(pwd)/common/skills"
if (! stat -q "$source" > /dev/null) || [ "$(grealpath "$source")" != "$target" ]; then
  echo "creating symlink at ${source/$HOME/~}..."
  rm -f "$source"
  mkdir -p "$(dirname "$source")"
  ln -s "$target" "$source"
else
  echo "${source/$HOME/~} symlink already up-to-date"
fi

echo "done!"
