# what the fuck tmuxinator
# https://discourse.brew.sh/t/why-does-tmuxinator-sets-gem-home/7296/3
unset -v GEM_HOME

# for installed completions
fpath+=~/.zfunc
autoload -Uz compinit && compinit

# antigen
source <path_to_antigen.zsh>
source <path_to_dotfiles>/zsh/antigen-configuration.zsh

# dotfiles
source <path_to_dotfiles>/zsh/theme.zsh
source <path_to_dotfiles>/zsh/dotfiles.zsh
source <path_to_dotfiles>/zsh/specifics.zsh
